# Generated by Django 3.0 on 2022-10-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0002_auto_20221006_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=30)),
                ('prod_sku', models.CharField(max_length=10)),
                ('prod_price', models.IntegerField()),
                ('prod_quantity', models.IntegerField()),
                ('prod_image', models.ImageField(max_length=200, null=True, upload_to='photos/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
