# Generated by Django 3.0 on 2022-10-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0005_auto_20221012_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
