# Generated by Django 3.0 on 2022-10-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0007_auto_20221012_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
