# Generated by Django 3.0 on 2022-10-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0008_auto_20221012_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(max_length=200, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_price',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to='uploads'),
        ),
    ]
