# Generated by Django 3.0 on 2022-10-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0009_auto_20221014_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to='photos'),
        ),
    ]
