# Generated by Django 3.0 on 2022-11-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0011_auto_20221017_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='items_bought',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
