# Generated by Django 3.0 on 2022-11-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smapp', '0013_retailerdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='retailerdata',
            table='retailerData',
        ),
    ]
